### PR TITLE
Fix #370

### LINKED ISSUE #370: Cannot define closure return type after capture group
Cannot define closure return type hint after capture group (defining it before the capture group works, but PHP allows putting the type hint in both places):

```php
$a = function() use ($a): bool { return true; };
```

Res:
```
Fatal error: Uncaught ParseError: Syntax error, unexpected ':' in res://f.php on line 2, position 25
```

### PR DESCRIPTION
**Pull request by danog**

### CODE REVIEW

**Comment by danog** [comment]
Ping? <3<3<3

**Comment by dim-s** [comment]
@danog 

How about this:

```php
$a = function(): bool use (&$a): bool { return true; };

var_dump($a());
```
Please check this case.

**Comment by dim-s** [comment]
And please remove `package/scripts/jppm` file changes.

**Comment by dim-s** [comment]
Thanks for the pull request, based on it I made a more correct fix.
https://github.com/jphp-group/jphp/commit/80489494597af6503df23db91855f01a021fb97b

**Pull request closed without merging**
