### PR TITLE
Pass the Environment and TraceInfo everywhere.

### PR DESCRIPTION
**Pull request by nstdio**
The lack of Environment information was preventing the project to be compatible with the original PHP.
This commit can be considered as a replacement of `Environment#current`.

Also added test for string offsets.

### CODE REVIEW

**Comment by nstdio** [comment]
Resolves #302

**Comment by dim-s** [comment]
Wow...

We need to return the valueOfIndex method without env, so as not to break backward compatibility, but mark them as deprecated methods.

**Comment by dim-s** [comment]
And you need to resolve conflicts...

**Comment by nstdio** [comment]
:+1:

**Comment by nstdio** [comment]
@dim-s Done.

**Pull request merged**
